### PR TITLE
My part 1 solution

### PR DESCRIPTION
**Pull request by chopmo**
Sorry, I don't know how to limit this PR to only some files. Feel free to disregard the answers file. 

However, I would love to get a little feedback on `RubyLs::Application`. As always when writing code like this, I'm unsure of what to put in instance vars and what to pass around as method arguments. I'm not 100% happy with the way the code is factored, but I'm also not sure how to improve it. Maybe by extracting some concerns into separate classes? 

I also rewrote the the test runner to output lots of info if a test fails. This was very useful during development.

### CODE REVIEW

**Comment by practicingruby** [comment]
Nice work! This seems to be at least somewhat based on the ideas in the article, and for that reason it's not all that different than the solution I'm going to produce for this problem.

I agree, decomposing it into a couple distinct objects would probably help. Feel free to take a crack at that yourself, or wait to see my solution when it's ready because I think i'll try to address that problem in my own code. However, I need to get farther into the problem myself before I can suggest good cut points. :grin: 

I think I'll borrow your `compare` method (with credit of course), because it definitely makes sense to have a better test runner. I have a minimal helper right now, but I would eventually need to build something similar to what you did here before completing the problem.

**Comment by practicingruby** [comment]
Although it's not covered by the tests, it looks like this solution may not properly handle things like `ls somedir`. I'm struggling with thinking through how to implement that myself while preserving both the globbing functionality and the missing directory error behavior. 

Any thoughts?

**Comment by chopmo** [comment]
@sandal Thanks! Feel free to borrow anything you can use.

**Comment by practicingruby** [comment]
@chopmo see my solution in #3 for how I decomposed things. More discussion is welcome!

**Pull request merged**
