### PR TITLE
Implement a Ruby version of ls(1) satisfying the given tests

### PR DESCRIPTION
**Pull request by eregon**
Hello,
Here is a concise solution passing the given tests in 42 lines.

The output of `ls -l` is challenging and interesting, notably for mapping permissions to the textual representation, uid/gid to names and computing the padding of the size.

I used `-s` which "enables some switch parsing for switches after script name" to parse options and took the road of a Regexp to validate the options. Unfortunately `-s` cannot handle `-1` but this is not in the assignment, and not a needed feature anyway (one can always add `| cat` to achieve the same effect).

### CODE REVIEW

**Comment by practicingruby** [comment]
Nice work! It's definitely concise, although I wonder how easy it will be to change if you decided to implement more switches. :wink:

Some thoughts:
- It doesn't look like your tests and implementation consider exit codes for successful and unsuccessful command runs. Maybe try adding that? `ls` will exit with a non-zero code for both invalid switches and missing file or dir.
- I've never seen `ruby -s` before, very interesting! Also kind of scary though... it simply turns switches into global variables? Not sure if I'd want to use that for serious applications, but probably useful for quick hacks.
- Your conversion of the permissions to their text representation takes a similar approach to what I experimented with when building this exercise. I wonder if there is a cleaner way, but I haven't found it yet.
- If you'd like to refactor your code from a script into a more structured application, I'd be happy to give you another review!

**Comment by eregon** [comment]
Thanks, and indeed it would quickly become unmanageable with more nested `if`.
- I forgot about it but fixed it in the new commit.
- Yeah, I guess a good description would be RubySpec's https://github.com/rubyspec/rubyspec/blob/master/command_line/dash_s_spec.rb . I find it a nice shortcut when you just want simple flags/options (and `optparse` is rather verbose).
- I am not too happy with it either, but so much String/Integer (in base 8!) conversion almost never looks nice and concise.
- I like it quick and concise for this kind of task, but I will have a look at others' submissions.

Thank you for this review!

**Comment by practicingruby** [comment]
> I am not too happy with it either, but so much String/Integer (in base 8!) conversion almost never looks nice and concise.

Well, the fact that permission numbers are often represented in base 8 obscures the fact that it's actually a simple bitmap going on behind the curtain:

``` ruby
>> 0644.to_s(2)
=> "110100100"
```

At the bit level, the representation is nicely lined up in a pattern:

```
  U        G       W
r w x   r w x   r w x
1 1 0   1 0 0   1 0 0
```

I feel like I'm missing an obvious transformation from the binary representation to the human readable rwx string. Let me know if you think of anything, otherwise we can hope some other solution nails it!

I'll leave this pull request open until two weeks from now when i release my own solution, so it's easier to find for others who want to compare it to their own.

**Comment by eregon** [comment]
Indeed, I missed that, I somehow thought the order would be reversed under the byte level.
Well, in that case, we should use more maths and less Strings:

``` ruby
perms = (%[r w x] * 3).map.with_index { |p,i|
  stat.mode[8-i] == 1 ? p : '-'
}.join
```

(The 8 is `9-1` because we take reverse indexes, we could also reverse `rwx` and at the end but it looks weird.)
It also has the advantage of not caring about higher permission bits nor needing any padding (e.g. if user perms are 0).

**Comment by eregon** [comment]
One could also "cheat" on BSD and use FFI and `strmode(3)`:

``` ruby
require 'ffi'
module StrMode
  extend FFI::Library
  ffi_lib FFI::Library::LIBC
  attach_function :strmode, [ :int, :pointer ], :void
end
perms = " " * 12
StrMode.strmode(0100644, perms)
puts perms # => "-rw-r--r--"
```

Seeing the [source](https://github.com/danielj7/gnulib/blob/master/lib/filemode.c#L95-L116) in gnulib, I find my above implementation quite nice.

**Comment by practicingruby** [comment]
``` ruby
perms = (%[r w x] * 3).map.with_index { |p,i|
  stat.mode[8-i] == 1 ? p : '-'
}.join
```

Something along these lines is what I had hoped to see. Thanks!

**Comment by practicingruby** [comment]
Although it's not covered by the tests, it looks like this solution may not properly handle things like `ls somedir`. I'm struggling with thinking through how to implement that myself while preserving both the globbing functionality and the missing directory error behavior. 

Any thoughts?

**Comment by eregon** [comment]
(The code before should be `%w` `[r w ...` (the `w` was missing)
Here you go, but definitely hacky! (chdir)

On intent I do not support multiple missing files like `ls(1)`, I prefer a fail-fast way.
Neither multiple arguments containing a directory, as this needs the `:<dir>` notation and starts using fancy spaces.

**Comment by practicingruby** [comment]
Thanks @eregon. This is also how @chopmo solved it in #2.

**Pull request closed without merging**
